server:
    port: 8080

spring:
    profiles: prod
    data:
        mongodb:
            mode: cluster
            host: localhost
            port: 27017
            databaseName: ithings
            #username: ithings
            #password: ithings
            #gridFsDatabase:
        
        elasticsearch:
            clusterName: ithings
            clusterNodes: 

    datasource:
        uniqueId: one
        dataSourceClassName: org.mariadb.jdbc.MySQLDataSource
        url: jdbc:mariadb://192.168.22.22:3306/iThingsDemo
        databaseName: iThingsDemo
        serverName: 192.68.22.22
        username: root
        password: s3cret

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.format_sql: false
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: ch.ithings.demo.config.hazelcast.HazelcastCacheRegionFactory
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
            hibernate.jdbc.batch_size: 3000
            hibernate.order_updates: true
            hibernate.order_inserts: true
            hibernate.max_fetch_depth: 1
            hibernate.default_schema: public
            hibernate.enable_lazy_load_no_trans: true
            hibernate.multiTenancy: SCHEMA
            hibernate.multi_tenant_connection_provider: ch.ithings.demo.config.data.MultiTenantConnectionProviderImpl
            hibernate.tenant_identifier_resolver: ch.ithings.demo.config.data.CurrentTenantIdentifierResolverImpl

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true


metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600
    hazelcast:
        debug: false
        stickySession: false
        backupCount: 1
